#!/usr/bin/env python3
"""Generates config.yaml's lists and leaves it with the kit's knobs set.

    python3 tools/skills-knob.py --image nousresearch/hermes-agent:v2026.7.30
    python3 tools/skills-knob.py --agent /path/to/the/agent/data
    python3 tools/skills-knob.py --agent <data> --apply <config.yaml>
    python3 tools/skills-knob.py --toolsets --image <tag>   ← the other generated list

`--apply` leaves the config COMPLETE —skills, platform_hints,
display.file_mutation_verifier and the three platform_toolsets—, each block
idempotent and without overwriting what belongs to that agent. Migrating an
agent is that one command, not copying blocks by hand from
compose/config.base.yaml.

WHY GENERATED AND NOT BY HAND: there are ~70 names and they change with every
engine version. A hand-written list goes stale on the first bump and nobody
notices — exactly what this kit doesn't do. The policy is one line ("all off
except the document-reading ones") and the list comes from the source.

WHERE THE ENGINE'S SKILLS COME FROM. They live in the IMAGE, at
/opt/hermes/skills, and `skills_sync.py` COPIES them to data/skills/ on every
container start (docker/stage2-hook.sh). So data/skills/ mixes three origins:

    from the image  → data/skills/<category>/<skill>/   noted in .bundled_manifest
    from the kit     → ours (today also there; see skills.external_dirs)
    from the client  → whatever the agent wrote for THAT business

That's why the generator NEVER lists data/skills/: it would turn off the
client's skills. The two valid sources are the image (`--image`, authoritative
for a tag, works before installing anything) and an already-set-up agent's
.bundled_manifest (`--agent`, offline and without docker, says what THAT
agent has seeded).

The ones left on are in compose/skills-allowed.txt. `agent-check.py` closes
the loop: it fails if an agent has an engine skill turned on outside that
list.
"""
import argparse
import datetime
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

KIT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALLOWED_TXT = os.path.join(KIT, "compose", "skills-allowed.txt")

# Where the compose mounts the kit's skills, read-only. It goes here inside
# and not in a separate `skills:` block because YAML doesn't allow the same
# key twice: with two `skills:` the last one wins and the other is lost with
# NO WARNING.
EXTERNAL_DIR = "/opt/kit/skills"

# The generated block lives between these two markers, like the SOUL's
# kit:base: that way it can be replaced without touching the rest of the
# config, and it's clear where it came from.
BLOCK_START = "# <<< generated by tools/skills-knob.py — do not hand-edit"
BLOCK_END = "# >>> end of the generated block"

# The generated block's provenance line: where THIS list came from. It gets
# written into the file (it's what's left for whoever audits it) and is
# EXCLUDED from the comparison that decides whether the block changed:
# otherwise, alternating --image/--agent with the identical list would mark
# the block as "replaced".
SOURCE_LINE = re.compile(r"^#   source: .*$", re.M)

# Fallback if the file isn't there (a loose copy of the script). The source
# of truth is the file; this just keeps the script from lying by silence.
# WATCH OUT: tools/agent-check.py has the SAME fallback. If you touch one,
# touch the other — they've already drifted apart once (that one had four
# names and this one three).
ALLOWED_BY_DEFAULT = ("docx", "ocr-and-documents", "pdf", "xlsx")


def allowed(path=ALLOWED_TXT):
    """The engine skills left on, from compose/skills-allowed.txt."""
    try:
        with open(path, encoding="utf-8") as fh:
            names = {
                l.strip() for l in fh
                if l.strip() and not l.lstrip().startswith("#")
            }
        return names or set(ALLOWED_BY_DEFAULT)
    except OSError:
        return set(ALLOWED_BY_DEFAULT)


def from_image(tag):
    """The names of the skills the engine's image ships with.

    A single-command container, no volume and no network: lists the
    directories that have a SKILL.md under /opt/hermes/skills. Doesn't start
    anything up.
    """
    cmd = [
        "docker", "run", "--rm", "--network", "none", "--entrypoint", "sh", tag,
        "-c", 'find /opt/hermes/skills -name SKILL.md -printf "%h\\n" | sed "s|.*/||" | sort -u',
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
    except FileNotFoundError:
        raise SystemExit(
            "couldn't find docker. If you don't have it handy, use --agent <path>/data,\n"
            "which reads an already-set-up agent's .bundled_manifest."
        )
    if result.returncode != 0:
        raise SystemExit(
            f"docker couldn't read the image {tag}:\n{result.stderr.strip()[:400]}\n"
            "Is it pulled? `docker pull " + tag + "`"
        )
    return {l.strip() for l in result.stdout.splitlines() if l.strip()}


# The toolsets we do NOT want on the portal's platform, with the why. They
# get removed by INCLUSION (not by listing them) and not with
# `agent.disabled_toolsets`, because that key subtracts the toolset's static
# catalog, and `browser`'s includes `web_search` — turning it off that way
# takes web search down with it.
TOOLSETS_OUT = {
    "browser": "9 tools that in production return blank screenshots",
}


def platform_toolsets_resolved(tag):
    """The api_server's toolsets, resolved BY THE ENGINE and without what we remove.

    It's not built by intersecting catalogs —tried it, comes out wrong: it
    pulls in `cronjob`, `delegation` and `homeassistant`, which the bundle
    lists but we turn off, and it loses `kanban`, which isn't in the bundle
    and comes in through the explicit passthrough—. The engine is asked to
    resolve the platform the HISTORICAL way (`hermes-api-server` + `kanban`)
    and what we don't want gets subtracted from that. It's the same
    resolution that runs in production.
    """
    reference_config = (
        "toolsets:\n  - kanban\n"
        "agent:\n  disabled_toolsets:\n    - tts\n    - delegation\n    - cronjob\n"
        "platform_toolsets:\n  api_server:\n    - hermes-api-server\n    - kanban\n"
    )
    code = (
        "import json,sys,os; sys.path.insert(0,'/opt/hermes');"
        "from hermes_cli.config import load_config;"
        "from hermes_cli.tools_config import _get_platform_tools;"
        "print(json.dumps(sorted(_get_platform_tools(load_config(), 'api_server'))))"
    )
    tmp = tempfile.mkdtemp()
    try:
        with open(os.path.join(tmp, "config.yaml"), "w", encoding="utf-8") as fh:
            fh.write(reference_config)
        cmd = ["docker", "run", "--rm", "--network", "none",
               "-v", f"{tmp}:/opt/data", "-e", "HERMES_HOME=/opt/data", "--user", "root",
               "--entrypoint", "/opt/hermes/.venv/bin/python", tag, "-c", code]
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
        except FileNotFoundError:
            raise SystemExit("couldn't find docker, and this list comes from the engine's image")
        if result.returncode != 0:
            raise SystemExit(f"docker couldn't read {tag}:\n{result.stderr.strip()[:400]}")
        return json.loads(result.stdout.strip().splitlines()[-1])
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


PLATFORMS = ("api_server", "telegram", "cron")


def toolsets_block(names, tag):
    """The `platform_toolsets` for all THREE platforms, ready to paste.

    All three carry the same list: it's the same agent handling the portal,
    Telegram and the flows, and a browser that returns blank pages fails the
    same way on all three.
    """
    kept = [n for n in names if n not in TOOLSETS_OUT]
    out = [n for n in names if n in TOOLSETS_OUT]
    lines = [
        "# GENERATED: the portal bundle's expansion minus what we remove, and the",
        "# same list for all three platforms.",
        f"#   source: image {tag}",
        "#   removed: " + (", ".join(f"{n} ({TOOLSETS_OUT[n]})" for n in out) or "none"),
        "#",
        "# The expanded list is used instead of the bundle's name because removing a",
        "# toolset with `agent.disabled_toolsets` subtracts its static catalog, and",
        "# `browser`'s includes `web_search`: it would take web search down with it.",
        "# And it goes toolset by toolset because a list that only names bundles",
        "# doesn't mention any configurable toolset: the engine never enters",
        "# explicit mode and falls back to the default, i.e. everything on.",
        "platform_toolsets:",
    ]
    for plat in PLATFORMS:
        lines.append(f"  {plat}:")
        lines += [f"    - {n}" for n in kept]
    return "\n".join(lines)


def from_agent(data):
    """The names THAT agent has seeded, from .bundled_manifest.

    Written by the engine itself when it copies the image's skills, formatted
    as `name:hash`. It's what agent-check.py looks at, because it doesn't
    need docker.
    """
    path = os.path.join(data, "skills", ".bundled_manifest")
    if not os.path.isfile(path):
        raise SystemExit(
            f"{path} doesn't exist.\n"
            "The engine writes that file on the first boot: if the agent has\n"
            "never started yet, generate the list from the image with --image."
        )
    with open(path, encoding="utf-8") as fh:
        return {l.split(":", 1)[0].strip() for l in fh if l.strip()}


def skills_block(names, source, allowed_set):
    """The whole `skills:` block, ready to paste into config.yaml.

    The COMPLETE key —`disabled` and `external_dirs`— goes out on purpose: if
    the config had two `skills:`, YAML keeps the last one and the other
    disappears with no warning.

    `source` gets WRITTEN into the block. For a while it only lived in
    stdout —so alternating `--image` and `--agent` wouldn't mark the block as
    changed with an identical list— and the fix was worse than the problem:
    running the command the config itself documents
    (`--image <tag> --apply compose/config.base.yaml`) overwrote
    `source: image nousresearch/hermes-agent:v2026.7.30` with generic text.
    Meaning the file read for auditing was losing exactly the data it gets
    read for, and on top of that when bumping the tag, which is when it
    matters. Comparing without the provenance gets solved at comparison time,
    not at write time: see `what_changed`.
    """
    disabled_list = sorted(names - allowed_set)
    kept = sorted(names & allowed_set)
    missing = sorted(allowed_set - names)

    lines = [
        BLOCK_START,
        f"#   source: {source}",
        f"#   disabled: {len(disabled_list)} · enabled: {', '.join(kept) or 'none'}",
        "#",
        "# Regenerate when bumping the engine's tag:",
        "#   python3 tools/skills-knob.py --image <tag> --apply compose/config.base.yaml",
        "#",
        "# A business agent doesn't send mail on its own (himalaya), doesn't post",
        "# (xurl), doesn't run anyone's smart home, and doesn't know how to operate its",
        "# own engine (hermes-agent, computer-use, claude-code). Each of those is",
        "# surface we didn't ask for, that doesn't go through the guard, and that also",
        "# gets paid for on every call to the model: the skills index is ~9 KB of the",
        "# prompt.",
        "#",
        "# To turn one on for a client: take it off this list, note why in THAT",
        "# agent's repo, and add it to compose/skills-allowed.txt ONLY if the",
        "# decision holds for everyone.",
        "skills:",
        "  disabled:",
    ]
    lines += [f"    - {n}" for n in disabled_list]
    if missing:
        lines.append(
            "  # WATCH OUT: " + ", ".join(missing) + " is in skills-allowed.txt but "
            "this engine version doesn't ship it."
        )
    lines += [
        "  # SELF-IMPROVEMENT every 25 turns, not every 10. The fork that writes",
        "  # skills fires on work VOLUME, not quality (turn_finalizer.py:633), so",
        "  # the more an agent suffers without the right tool, the more likely it",
        "  # is to canonize the suffering. It doesn't get turned off —it's the",
        "  # only signal that a production agent is missing something—: it gets",
        "  # bounded and harvested instead. No default declared in",
        "  # config_defaults.py: it lives as the .get(..., 10) in",
        "  # agent_init.py:1706-1710.",
        "  creation_nudge_interval: 25",
        "  # The kit's skills, mounted read-only from the compose. They live",
        "  # outside data/skills/ so the agent can't rewrite them and so the",
        "  # curator doesn't archive them after 90 days unused.",
        "  external_dirs:",
        f"    - {EXTERNAL_DIR}",
        BLOCK_END,
    ]
    return "\n".join(lines)


def without_source(block_text):
    """The block without its provenance line: what has to be compared.

    What decides whether an agent's configuration changes is THE LIST, not
    where we read it from. Two runs —one against the image, another against
    that same agent's `.bundled_manifest`— give the same list and have to
    report "already the same", even if the provenance that ends up written
    differs.
    """
    return SOURCE_LINE.sub("", block_text).strip()


def what_changed(old, new):
    """What to report about the skills block: the list, and the provenance separately."""
    if old.strip() == new.strip():
        return "already the same"
    if without_source(old) == without_source(new):
        return "same list, source up to date"
    return "replaced"


def top_level_block(text, key):
    """A YAML's `key:` block, with the comments that precede it.

    The comments are included because in this repo they ARE the evidence: the
    one on `platform_hints` explains what engine text we're replacing and
    where it lives in its code.
    """
    m = re.search(rf"^{re.escape(key)}:[ \t]*$", text, re.M)
    if not m:
        return ""
    rest = text[m.end():]
    end = re.search(r"^\S", rest, re.M)
    body = text[m.start():] if end is None else text[m.start(): m.end() + end.start()]
    # Upward: the comment lines stuck to the key.
    start = m.start()
    lines = text[:start].splitlines(keepends=True)
    while lines and lines[-1].lstrip().startswith("#"):
        start -= len(lines[-1])
        lines.pop()
    return text[start: m.start()] + body


def kit_config():
    """The kit's canonical config, the source of the blocks that aren't generated."""
    base = os.path.join(KIT, "compose", "config.base.yaml")
    try:
        with open(base, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return ""


def top_level_value(text, key, subkey):
    """The scalar value of `key: subkey:`, looked up inside THAT block."""
    m = re.search(rf"^{re.escape(key)}:[ \t]*$", text, re.M)
    if not m:
        return ""
    rest = text[m.end():]
    nxt = re.search(r"^\S", rest, re.M)
    block = rest[: nxt.start()] if nxt else rest
    m2 = re.search(rf"^[ \t]+{re.escape(subkey)}:[ \t]*(.*)$", block, re.M)
    return m2.group(1).strip() if m2 else ""


def block_span(text, key):
    """(start, end) of the `key:` block, including its comments above."""
    m = re.search(rf"^{re.escape(key)}:[ \t]*$", text, re.M)
    if not m:
        return None
    rest = text[m.end():]
    nxt = re.search(r"^\S", rest, re.M)
    end = m.end() + (nxt.start() if nxt else len(rest))
    start = m.start()
    lines = text[:start].splitlines(keepends=True)
    while lines and lines[-1].lstrip().startswith("#"):
        start -= len(lines[-1])
        lines.pop()
    return start, end


def set_block(text, key, new):
    """Replaces the `key:` block with `new`, or appends it at the end.

    Replacing instead of appending is the point: two identical keys in a YAML
    don't raise an error, the last one wins and the other is lost with no
    warning.
    """
    new = new.rstrip("\n") + "\n"
    span = block_span(text, key)
    if span is None:
        return text.rstrip("\n") + "\n\n" + new, "added"
    start, end = span
    old = text[start:end]
    tail = "\n\n" if text[end:].strip() else "\n"
    if old.strip() == new.strip():
        # The content is already there; it may be missing the blank line
        # below, which lives outside what's compared (an earlier version of
        # this ate it).
        if old == old.strip("\n") + tail:
            return text, "already the same"
        return text[:start] + old.strip("\n") + tail + text[end:], "same, spacing normalized"
    # One blank line before whatever follows, and only one. The span reaches
    # up to the next block's comment, so without this the replacement eats
    # the blank line that separated them.
    return text[:start] + new.rstrip("\n") + tail + text[end:], "replaced"


def only_once(text, path, keys):
    """Refuses if any top-level key is repeated.

    With two `platform_toolsets:` we'd replace the first and leave the
    second, and YAML keeps the LAST one: the config would say one thing and
    the engine would read another, with this script reporting "replaced" and
    exiting 0.
    """
    repeated = [c for c in keys
                if len(re.findall(rf"^{re.escape(c)}:", text, re.M)) > 1]
    if repeated:
        raise SystemExit(
            f"{path} has repeated top-level key(s): "
            + ", ".join(repeated)
            + ". In YAML that isn't an error —the last one wins and the other "
            "is lost—, so I'm not touching anything: leave a single one of "
            "each and run again."
        )


def valid_yaml(text, path):
    """Parses the config before touching it, if PyYAML is around.

    Everything else here is text and regex, which doesn't notice a broken
    YAML: without this, a config with cut indentation gets rewritten anyway
    and the script reports success. If PyYAML isn't there (the operator's
    machine might not have it), it moves on: it's an extra check, not a new
    requirement.
    """
    try:
        import yaml
    except ImportError:
        return "no PyYAML: couldn't parse it"
    try:
        yaml.safe_load(text)
    except Exception as exc:
        raise SystemExit(
            f"{path} isn't valid YAML and I'm not going to rewrite it:\n  {exc}\n"
            "Fix it first — if I touched it, it would stay broken and with my changes on top."
        )
    return ""


def save(path, text):
    """Writes the config without ever leaving it half-done, keeping a copy of the old one.

    `open(path, "w")` truncates and then writes: if the process dies in the
    middle, a LIVE agent's config is left cut off. It's written next to it and
    moved with `os.replace`, which is atomic —the same thing the engine does
    in `atomic_config_write`—, and a copy is kept beforehand in case the new
    content turns out to be the problem.
    """
    backup = ""
    if os.path.isfile(path):
        agent = os.path.basename(os.path.dirname(os.path.dirname(os.path.abspath(path))))
        dest = os.path.join(KIT, "config-backups")
        os.makedirs(dest, exist_ok=True)
        # Seconds were enough to overwrite itself: two runs in a row left ONE
        # file, and the one that remained was the second state — i.e. the
        # original got lost. Milliseconds, and if it still collides, a
        # suffix.
        stamp = f"{datetime.datetime.now():%Y%m%d-%H%M%S-%f}"[:-3]
        backup = os.path.join(dest, f"{agent}-{stamp}.yaml")
        n = 2
        while os.path.exists(backup):
            backup = os.path.join(dest, f"{agent}-{stamp}-{n}.yaml")
            n += 1
        shutil.copy2(path, backup)
    tmp = path + ".tmp"
    try:
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, path)
    finally:
        # If something broke between the write and the replace, the .tmp
        # doesn't get left lying around in the agent's volume for someone to
        # find later with no idea what it is. (A kill -9 leaves it anyway: no
        # try catches that, and the next run overwrites it.)
        if os.path.exists(tmp):
            try:
                os.remove(tmp)
            except OSError:
                pass
    return backup


def set_subkey(text, key, subkey, value):
    """Sets `key: subkey: value` without touching the rest of the block.

    For `display:`, which can have other agent keys (`inline_diffs`, credit
    notices): replacing the whole block would take those down with it.
    """
    span = block_span(text, key)
    line = f"  {subkey}: {value}"
    if span is None:
        return text.rstrip("\n") + f"\n\n{key}:\n{line}\n", "added"
    start, end = span
    block = text[start:end]
    m = re.search(rf"^([ \t]+){re.escape(subkey)}:[ \t]*(.*)$", block, re.M)
    if m:
        if m.group(2).strip() == value:
            return text, "already the same"
        new_block = block[:m.start()] + f"{m.group(1)}{subkey}: {value}" + block[m.end():]
        return text[:start] + new_block + text[end:], "replaced"
    # The key exists but without that subkey: append it at the end of the block.
    new_block = block.rstrip("\n") + "\n" + line + "\n"
    return text[:start] + new_block + text[end:], "added"


def kit_platform_toolsets(agent_text):
    """The kit's `platform_toolsets` block, respecting platforms that aren't ours.

    Our three (api_server, telegram, cron) get overwritten with the kit's
    list. If the agent declares some other one —a platform this client uses
    that the kit doesn't know about— it's kept as-is: migrating doesn't mean
    deleting things from it.
    """
    kit = top_level_block(kit_config(), "platform_toolsets")
    if not kit:
        return ""
    span = block_span(agent_text, "platform_toolsets")
    if span is None:
        return kit
    block = agent_text[span[0]: span[1]]
    foreign = []
    for m in re.finditer(r"^  ([a-z_][a-z0-9_]*):[ \t]*$", block, re.M):
        if m.group(1) in PLATFORMS:
            continue
        rest = block[m.end():]
        nxt = re.search(r"^  \S", rest, re.M)
        foreign.append(block[m.start(): m.end() + (nxt.start() if nxt else len(rest))].rstrip("\n"))
    if not foreign:
        return kit
    return kit.rstrip("\n") + "\n" + "\n".join(foreign) + "\n"


def apply_config(block_text, path):
    """Leaves the config with ALL of the kit's knobs set, not just one.

    There are four blocks and they go together: an agent migrated halfway is
    the one that later shows up with the engine's "assume plain text", or
    with the browser turned on in Telegram, and nobody knows why. This used
    to apply two and the other two had to be copied by hand from
    compose/config.base.yaml.

    Each block is idempotent: if it's already the same it's left alone, if it
    differs it's replaced (never appended alongside: two identical keys in a
    YAML don't raise an error, the last one wins and the other is lost
    silently), and if it's missing it's added. Nothing that belongs to THAT
    agent gets overwritten — `model.base_url` with its own proxy, platforms
    the kit doesn't know about, other `display` keys.
    """
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    # Before touching anything: that it's YAML, and that there are no
    # repeated keys among the ones we're about to replace.
    yaml_note = valid_yaml(text, path)
    only_once(text, path,
              ("skills", "platform_hints", "platform_toolsets", "display"))
    kit = kit_config()
    actions = []

    # 1. skills (disabled + external_dirs), the only generated one, between markers.
    if BLOCK_START in text and BLOCK_END in text:
        start, end = text.index(BLOCK_START), text.index(BLOCK_END) + len(BLOCK_END)
        old = text[start:end]
        text = text[:start] + block_text + text[end:]
        actions.append(("skills", what_changed(old, block_text)))
    else:
        if re.search(r"^skills:", text, re.M):
            raise SystemExit(
                f"{path} already has a `skills:` block with no markers. Remove "
                "it by hand before applying: two `skills:` keys in a YAML "
                "don't raise an error, the last one wins and the other is "
                "lost silently."
            )
        text = text.rstrip("\n") + "\n\n" + block_text.rstrip("\n") + "\n"
        actions.append(("skills", "added"))

    # 2. platform_hints: the portal's preamble.
    hint = top_level_block(kit, "platform_hints")
    if hint:
        text, acc = set_block(text, "platform_hints", hint)
        actions.append(("platform_hints", acc))
    else:
        actions.append(("platform_hints", "WATCH OUT: not in compose/config.base.yaml"))

    # 3. display.file_mutation_verifier: just that key, without touching the rest.
    value = top_level_value(kit, "display", "file_mutation_verifier") or "false"
    text, acc = set_subkey(text, "display", "file_mutation_verifier", value)
    actions.append(("display.file_mutation_verifier", acc))

    # 4. platform_toolsets: all three platforms, keeping the foreign ones.
    pts = kit_platform_toolsets(text)
    if pts:
        text, acc = set_block(text, "platform_toolsets", pts)
        actions.append(("platform_toolsets", acc))
    else:
        actions.append(("platform_toolsets", "WATCH OUT: not in compose/config.base.yaml"))

    # The dead key: a `cron:` hanging off `platforms:` isn't read by anyone
    # (toolsets go in `platform_toolsets`), and confuses whoever sees it.
    span = block_span(text, "platforms")
    if span:
        block = text[span[0]: span[1]]
        m = re.search(r"^  cron:[ \t]*\n(    - .*\n)+", block, re.M)
        if m:
            text = text[:span[0]] + block[:m.start()] + block[m.end():] + text[span[1]:]
            actions.append(("platforms.cron (dead key)", "removed"))

    if all(acc == "already the same" for _, acc in actions):
        print(f"config was already up to date: {path}")
        for name, acc in actions:
            print(f"  {name:34} {acc}")
        return

    valid_yaml(text, path)          # and that what comes out also parses
    backup = save(path, text)
    print(f"config updated: {path}")
    for name, acc in actions:
        print(f"  {name:34} {acc}")
    if backup:
        print(f"  {'copy of the previous one':34} {backup}")
    if yaml_note:
        print(f"  ({yaml_note})")


def main():
    ap = argparse.ArgumentParser(
        description="Generates the disabled-skills list and leaves config.yaml "
                    "with all of the kit's knobs set.",
        epilog="With no arguments it uses the kit compose's image.",
    )
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--image", metavar="TAG", help="engine image tag")
    g.add_argument("--agent", metavar="DATA", help="path to an already-set-up agent's data/")
    ap.add_argument(
        "--apply", metavar="CONFIG",
        help="leave THAT config.yaml complete: skills, platform_hints, "
             "display.file_mutation_verifier and all three platform_toolsets",
    )
    ap.add_argument(
        "--toolsets", action="store_true",
        help="print the platform_toolsets for all three platforms instead of "
             "the skills list",
    )
    args = ap.parse_args()

    if args.toolsets:
        tag = args.image or "nousresearch/hermes-agent:v2026.7.30"
        print(toolsets_block(platform_toolsets_resolved(tag), tag))
        return 0

    if args.agent:
        names = from_agent(os.path.abspath(args.agent))
        source = f"{os.path.abspath(args.agent)}/skills/.bundled_manifest"
    else:
        tag = args.image or "nousresearch/hermes-agent:v2026.7.30"
        names = from_image(tag)
        source = f"image {tag}"

    if not names:
        raise SystemExit(f"didn't find any engine skill in {source}")
    text = skills_block(names, source, allowed())
    if args.apply:
        # The provenance is reported on screen AND left written in the block:
        # what nobody keeps is the screen.
        print(f"skills list read from: {source}")
        apply_config(text, args.apply)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
