#!/usr/bin/env node
/* Render an on-brand Instagram image to PNG, with no headless browser.
 *
 * Typography is NEVER generated by an image model: they spell badly, and a card
 * shipped with a typo in 96pt is worse than not posting. Anything with words on
 * it is laid out here, deterministically, with the brand's real colours and real
 * font files -- the ones brand-kit already downloaded.
 *
 * Reads a JSON spec on stdin, writes a PNG, prints a JSON result.
 *
 *   echo '{"plantilla":"portada","titulo":"..."}' \
 *     | node render.mjs --out /opt/data/workspace/piezas/tapa.png
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { dirname, join, extname } from "node:path";

const KIT_DIR = dirname(new URL(import.meta.url).pathname);
const { createRequire } = await import("node:module");

/* El motor de render se instala en el DESPLIEGUE, no en tiempo de ejecucion, y
 * vive afuera de la skill porque kit-skills/ se monta de solo lectura y trae
 * binarios nativos. Se busca en varios lugares para que el mismo script ande en
 * el agente, en un staging y en la maquina de uno. */
function loadTakumi() {
  const bases = [
    process.env.TAKUMI_DIR,
    join(KIT_DIR, "..", "vendor"),
    "/opt/kit/render",
    KIT_DIR,
  ].filter(Boolean);
  const tried = [];
  for (const base of bases) {
    try {
      const req = createRequire(join(base, "package.json"));
      return { core: req("@takumi-rs/core"), helpers: req("@takumi-rs/helpers"), base };
    } catch { tried.push(base); }
  }
  console.log(JSON.stringify({
    ok: false,
    error: "no encuentro @takumi-rs (el motor de render)",
    hint: "se instala en el despliegue: npm i --prefix /opt/kit/render @takumi-rs/core @takumi-rs/helpers",
    busque_en: tried,
  }, null, 2));
  process.exit(1);
}

// Sizes Instagram actually renders. 4:5 takes the most feed real estate.
const CANVAS = {
  feed: { width: 1080, height: 1350 },
  carrusel: { width: 1080, height: 1350 },
  historia: { width: 1080, height: 1920 },
  reel: { width: 1080, height: 1920 },
};

// Stories put interface buttons over the top and bottom of the screen.
const SAFE_MARGIN = { historia: 250, reel: 250, feed: 0, carrusel: 0 };

const PLANTILLAS = ["portada", "slide", "cita", "dato"];

function parseArgs(argv) {
  const out = { formato: "feed", out: "", brandDir: process.env.BRAND_DIR || "/opt/data/workspace/brand" };
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--formato") out.formato = argv[++i];
    else if (argv[i] === "--out") out.out = argv[++i];
    else if (argv[i] === "--brand-dir") out.brandDir = argv[++i];
  }
  return out;
}

function hexToRgba(hex, alpha = 255) {
  const clean = String(hex || "").replace("#", "");
  if (clean.length !== 6) return null;
  return [parseInt(clean.slice(0, 2), 16), parseInt(clean.slice(2, 4), 16),
          parseInt(clean.slice(4, 6), 16), alpha];
}

function luminance(hex) {
  const [r, g, b] = hexToRgba(hex).slice(0, 3).map((v) => v / 255);
  const ch = (c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
  return 0.2126 * ch(r) + 0.7152 * ch(g) + 0.0722 * ch(b);
}

/** White or black, whichever is actually readable on this background.
 *  Same WCAG maths as brand-kit: the card can be off-brand, never illegible. */
function inkFor(background) {
  const l = luminance(background);
  const onWhite = 1.05 / (l + 0.05);
  const onBlack = (l + 0.05) / 0.05;
  return onWhite >= onBlack ? "#ffffff" : "#111111";
}

function loadBrand(brandDir) {
  const file = join(brandDir, "brand.json");
  if (!existsSync(file)) return null;
  try { return JSON.parse(readFileSync(file, "utf8")); } catch { return null; }
}

function registerBrandFonts(renderer, brandDir, brand) {
  const dir = join(brandDir, "fonts");
  const loaded = [];
  if (existsSync(dir)) {
    for (const name of readdirSync(dir)) {
      if (![".woff2", ".woff", ".ttf", ".otf"].includes(extname(name).toLowerCase())) continue;
      try { renderer.registerFont(readFileSync(join(dir, name))); loaded.push(name); }
      catch { /* una fuente rota no puede voltear la pieza entera */ }
    }
  }
  const faces = ((brand || {}).typography || {}).faces || [];
  const family = faces.length ? faces[0].family : null;
  return { loaded, family };
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const spec = JSON.parse(readFileSync(0, "utf8"));
  const fail = (error, hint) => {
    console.log(JSON.stringify({ ok: false, error, hint }, null, 2));
    process.exit(1);
  };

  if (!args.out) fail("falta --out");
  if (!PLANTILLAS.includes(spec.plantilla))
    fail(`plantilla desconocida: ${spec.plantilla}`, `las que hay: ${PLANTILLAS.join(", ")}`);
  const canvas = CANVAS[args.formato];
  if (!canvas) fail(`formato desconocido: ${args.formato}`, `los que hay: ${Object.keys(CANVAS).join(", ")}`);

  const brand = loadBrand(args.brandDir);
  if (!brand) {
    fail("no hay kit de marca en " + args.brandDir,
         "corre la skill brand-kit primero: sin colores ni tipografia la pieza no es de nadie");
  }

  const takumi = loadTakumi();
  const { Renderer } = takumi.core;
  const { container, text, rgba } = takumi.helpers;

  const warnings = [];
  const renderer = new Renderer({});
  const fonts = registerBrandFonts(renderer, args.brandDir, brand);
  if (!fonts.loaded.length)
    warnings.push("el kit no tiene archivos de tipografia: la pieza sale con la tipografia por defecto");

  const roles = ((brand.colors || {}).roles) || {};
  const background = spec.fondo || roles.primary || "#111111";
  const ink = spec.tinta || inkFor(background);
  if (!hexToRgba(background)) fail(`color de fondo invalido: ${background}`);

  /* El acento pinta el numero grande, el contador y el CTA, asi que tambien
   * tiene que ser legible: un coral claro sobre blanco da 1,2:1 y el numero
   * desaparece, con la pieza informando 18:1 porque ese numero era la TINTA
   * contra el fondo. Se valida todo lo que se pinta, no solo lo principal.
   * Umbral 3:1, que es el de WCAG para texto grande, que es lo que el acento es. */
  const ratio = (a, b) => (Math.max(luminance(a), luminance(b)) + 0.05)
    / (Math.min(luminance(a), luminance(b)) + 0.05);
  let accent = roles.accent || ink;
  if (hexToRgba(accent) && ratio(accent, background) < 3) {
    const alternative = [roles.primary, roles.secondary, ink]
      .find((c) => hexToRgba(c) && ratio(c, background) >= 3) || ink;
    warnings.push(`el acento ${accent} da ${ratio(accent, background).toFixed(2)}:1 sobre el fondo `
      + `y no se leeria; uso ${alternative}`);
    accent = alternative;
  }

  const pad = Math.round(canvas.width * 0.09);
  const safe = SAFE_MARGIN[args.formato] || 0;
  const esVertical = canvas.height / canvas.width > 1.5;   // 9:16

  /* EN 9:16 EL CONTENIDO VA AL CENTRO, NO ABAJO. Alinear al pie es correcto en
   * una placa 4:5, donde el bloque de texto ocupa media pieza. En una historia
   * el mismo criterio, sumado a los 250px de margen seguro, deja el texto en una
   * franja entre el 61% y el 82% de la altura: el 61% de arriba queda muerto y
   * abajo queda un hueco. Se ve como una diapositiva mal pegada, que es
   * exactamente como se veian las dos primeras historias que salieron.
   * Ademas el ojo y el pulgar del que mira estan en el medio, no en el pie. */
  const alineacion = (esVertical || spec.plantilla === "dato") ? "center" : "flex-end";
  const font = fonts.family || undefined;
  const paint = (hex) => rgba(...hexToRgba(hex));

  // OJO: la firma es text(cadena, estilo) y el estilo va DIRECTO. Envolverlo en
  // {style:{...}} no falla: se ignora en silencio y la pieza sale con todo en
  // 16px negro, que es exactamente como se ve un renderer "andando" y roto.
  const line = (value, size, opts = {}) => text(String(value), {
    fontSize: size,
    lineHeight: opts.lineHeight || 1.08,
    color: paint(opts.color || ink),
    fontFamily: font,
    fontWeight: opts.weight || 700,
    ...(opts.style || {}),
  });

  const children = [];
  const escala = esVertical ? 1.12 : 1;
  const titleSize = Math.round(canvas.width * (spec.plantilla === "dato" ? 0.075 : 0.085) * escala);

  if (spec.plantilla === "slide" && spec.numero) {
    children.push(line(`${spec.numero}${spec.total ? `/${spec.total}` : ""}`,
      Math.round(canvas.width * 0.038), { color: accent, style: { marginBottom: 24 } }));
  }
  if (spec.plantilla === "dato" && spec.numero) {
    children.push(line(spec.numero, Math.round(canvas.width * 0.22),
      { color: accent, lineHeight: 1, style: { marginBottom: 16 } }));
  }
  if (spec.plantilla === "cita") {
    children.push(line("“", Math.round(canvas.width * 0.18),
      { color: accent, lineHeight: 0.9, style: { marginBottom: -20 } }));
  }
  if (!spec.titulo) fail("falta 'titulo' en el spec");
  children.push(line(spec.titulo, titleSize,
    { style: spec.plantilla === "cita" ? { fontStyle: "italic" } : {} }));

  if (spec.bajada) {
    children.push(line(spec.bajada, Math.round(canvas.width * 0.038 * escala),
      { weight: 400, lineHeight: 1.35, style: { marginTop: 28, opacity: 0.92 } }));
  }
  if (spec.pie) {
    children.push(line(spec.pie, Math.round(canvas.width * 0.03),
      { weight: 600, color: accent, style: { marginTop: 44 } }));
  }

  const node = container({
    style: {
      width: canvas.width, height: canvas.height, display: "flex", flexDirection: "column",
      justifyContent: alineacion,
      paddingLeft: pad, paddingRight: pad,
      paddingTop: pad + safe, paddingBottom: pad + safe,
      backgroundColor: paint(background),
    },
    children,
  });

  return renderer.render(node, { width: canvas.width, height: canvas.height, format: "png" })
    .then((png) => {
      mkdirSync(dirname(args.out), { recursive: true });
      writeFileSync(args.out, png);
      console.log(JSON.stringify({
        ok: true,
        archivo: args.out,
        bytes: png.length,
        medidas: `${canvas.width}x${canvas.height}`,
        colores: { fondo: background, tinta: ink, acento: accent },
        contraste: Number((Math.max(luminance(background), luminance(ink)) + 0.05)
          / (Math.min(luminance(background), luminance(ink)) + 0.05)).toFixed(2) + ":1",
        tipografia: fonts.family || "por defecto",
        avisos: warnings,
      }, null, 2));
    });
}

main();
