#!/usr/bin/env node
/* Render an on-brand Instagram image to PNG, with no headless browser.
 *
 * THE AGENT COMPOSES; THIS SCRIPT GUARANTEES. The first version owned the
 * layout -- four fixed templates with fixed slots -- and every piece came out
 * identical, which is a worse failure than an ugly piece: a feed where all ten
 * posts look the same reads as one post repeated.
 *
 * So the split is:
 *   the agent decides  → blocks, order, scale, weight, alignment, colour roles,
 *                        spacing, rules, background
 *   the script decides → canvas size, safe margins, that every colour it paints
 *                        is legible on its background, and that the fonts and
 *                        palette come from the brand kit and nowhere else
 *
 * Typography is NEVER generated by an image model: they spell badly, and a card
 * shipped with a typo in 96pt is worse than not posting.
 *
 * Reads a JSON spec on stdin, writes a PNG, prints a JSON result.
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { dirname, join, extname } from "node:path";

const KIT_DIR = dirname(new URL(import.meta.url).pathname);
const { createRequire } = await import("node:module");

function loadTakumi() {
  const bases = [process.env.TAKUMI_DIR, join(KIT_DIR, "..", "vendor"), "/opt/kit/render", KIT_DIR]
    .filter(Boolean);
  const tried = [];
  for (const base of bases) {
    try {
      const req = createRequire(join(base, "package.json"));
      return { core: req("@takumi-rs/core"), helpers: req("@takumi-rs/helpers") };
    } catch { tried.push(base); }
  }
  console.log(JSON.stringify({
    ok: false,
    error: "no encuentro @takumi-rs (el motor de render)",
    hint: "lo instala tools/instalar-render.sh en el destino",
    busque_en: tried,
  }, null, 2));
  process.exit(1);
}

const CANVAS = {
  feed: { width: 1080, height: 1350 },
  carrusel: { width: 1080, height: 1350 },
  historia: { width: 1080, height: 1920 },
  reel: { width: 1080, height: 1920 },
};
// Instagram draws its own buttons over the top and bottom of a 9:16 screen.
const SAFE_MARGIN = { historia: 250, reel: 250, feed: 0, carrusel: 0 };

// Relative to canvas WIDTH, so a piece scales the same in 4:5 and 9:16.
const SCALES = { gigante: 0.20, titulo: 0.085, subtitulo: 0.055, bajada: 0.038, pie: 0.030 };
const VALIGN = { arriba: "flex-start", centro: "center", abajo: "flex-end" };
const HALIGN = { izquierda: "flex-start", centro: "center", derecha: "flex-end" };

/* Presets. Son un PUNTO DE PARTIDA, no una jaula: el agente pide uno y despues
 * cambia lo que quiera, o manda `bloques` directamente y no usa ninguno. */
const PRESETS = {
  portada: (s) => [
    { tipo: "texto", texto: s.titulo, escala: "titulo" },
    s.bajada && { tipo: "espacio", alto: 28 },
    s.bajada && { tipo: "texto", texto: s.bajada, escala: "bajada", peso: 400 },
    s.pie && { tipo: "espacio", alto: 44 },
    s.pie && { tipo: "texto", texto: s.pie, escala: "pie", peso: 600, color: "acento" },
  ],
  slide: (s) => [
    s.numero && { tipo: "texto", texto: `${s.numero}${s.total ? `/${s.total}` : ""}`,
                  escala: "pie", peso: 700, color: "acento" },
    s.numero && { tipo: "espacio", alto: 24 },
    { tipo: "texto", texto: s.titulo, escala: "titulo" },
    s.bajada && { tipo: "espacio", alto: 28 },
    s.bajada && { tipo: "texto", texto: s.bajada, escala: "bajada", peso: 400 },
  ],
  dato: (s) => [
    { tipo: "texto", texto: s.numero, escala: "gigante", color: "acento", interlinea: 1 },
    { tipo: "espacio", alto: 16 },
    { tipo: "texto", texto: s.titulo, escala: "subtitulo" },
  ],
  cita: (s) => [
    { tipo: "texto", texto: "“", escala: "gigante", color: "acento", interlinea: 0.9 },
    { tipo: "texto", texto: s.titulo, escala: "subtitulo", italica: true },
    s.bajada && { tipo: "espacio", alto: 28 },
    s.bajada && { tipo: "texto", texto: s.bajada, escala: "pie", peso: 600, color: "acento" },
  ],
};

function parseArgs(argv) {
  const out = { formato: "feed", out: "", brandDir: process.env.BRAND_DIR || "/opt/data/workspace/brand" };
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--formato") out.formato = argv[++i];
    else if (argv[i] === "--out") out.out = argv[++i];
    else if (argv[i] === "--brand-dir") out.brandDir = argv[++i];
  }
  return out;
}

function hexToRgba(hex, alpha = 255) {
  const clean = String(hex || "").replace("#", "");
  if (!/^[0-9a-fA-F]{6}$/.test(clean)) return null;
  return [parseInt(clean.slice(0, 2), 16), parseInt(clean.slice(2, 4), 16),
          parseInt(clean.slice(4, 6), 16), alpha];
}

function luminance(hex) {
  const [r, g, b] = hexToRgba(hex).slice(0, 3).map((v) => v / 255);
  const ch = (c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
  return 0.2126 * ch(r) + 0.7152 * ch(g) + 0.0722 * ch(b);
}

const ratio = (a, b) => (Math.max(luminance(a), luminance(b)) + 0.05)
  / (Math.min(luminance(a), luminance(b)) + 0.05);

function inkFor(background) {
  return ratio("#ffffff", background) >= ratio("#111111", background) ? "#ffffff" : "#111111";
}

function loadBrand(brandDir) {
  const file = join(brandDir, "brand.json");
  if (!existsSync(file)) return null;
  try { return JSON.parse(readFileSync(file, "utf8")); } catch { return null; }
}

function registerBrandFonts(renderer, brandDir, brand) {
  const dir = join(brandDir, "fonts");
  const loaded = [];
  if (existsSync(dir)) {
    for (const name of readdirSync(dir)) {
      if (![".woff2", ".woff", ".ttf", ".otf"].includes(extname(name).toLowerCase())) continue;
      try { renderer.registerFont(readFileSync(join(dir, name))); loaded.push(name); }
      catch { /* una fuente rota no puede voltear la pieza entera */ }
    }
  }
  const faces = ((brand || {}).typography || {}).faces || [];
  return { loaded, family: faces.length ? faces[0].family : null };
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const spec = JSON.parse(readFileSync(0, "utf8"));
  const fail = (error, hint) => {
    console.log(JSON.stringify({ ok: false, error, hint }, null, 2));
    process.exit(1);
  };

  if (!args.out) fail("falta --out");
  const canvas = CANVAS[args.formato];
  if (!canvas) fail(`formato desconocido: ${args.formato}`, `hay: ${Object.keys(CANVAS).join(", ")}`);

  const brand = loadBrand(args.brandDir);
  if (!brand) fail("no hay kit de marca en " + args.brandDir,
                   "corré la skill brand-kit primero: sin colores ni tipografía la pieza no es de nadie");

  const { core, helpers } = loadTakumi();
  const { container, text, rgba } = helpers;
  const warnings = [];
  const renderer = new core.Renderer({});
  const fonts = registerBrandFonts(renderer, args.brandDir, brand);
  if (!fonts.loaded.length)
    warnings.push("el kit no tiene archivos de tipografía: la pieza sale con la tipografía por defecto");

  const roles = ((brand.colors || {}).roles) || {};
  const resolve = (name, fallback) => {
    if (!name) return fallback;
    const byRole = { primario: roles.primary, secundario: roles.secondary, acento: roles.accent,
                     fondo: roles.background, texto: roles.text, apagado: roles.muted };
    const hex = byRole[name] || name;
    return hexToRgba(hex) ? hex.toLowerCase() : fallback;
  };

  const background = resolve(spec.fondo, roles.primary || "#111111");
  const ink = resolve(spec.tinta, inkFor(background));

  /* LA GARANTIA QUE EL AGENTE NO PUEDE ROMPER: todo lo que se pinta se lee.
   * El agente elige el rol; si ese color no llega contra el fondo se reemplaza
   * por el primero que sí, y queda dicho en `avisos`. Sin esto, "que el agente
   * decida" termina en un coral sobre blanco a 1,25:1, que es invisible. */
  const MIN = { grande: 3, chico: 4.5 };
  const legible = (hex, grande, dondeSeUsa) => {
    const necesita = grande ? MIN.grande : MIN.chico;
    if (ratio(hex, background) >= necesita) return hex;
    const alternativa = [ink, roles.text, roles.primary, "#ffffff", "#111111"]
      .find((c) => c && hexToRgba(c) && ratio(c, background) >= necesita) || ink;
    warnings.push(`${dondeSeUsa}: ${hex} da ${ratio(hex, background).toFixed(2)}:1 sobre ${background} `
      + `(necesita ${necesita}) — uso ${alternativa}`);
    return alternativa;
  };

  // El agente manda `bloques`, o pide un preset y lo ajusta.
  let bloques = spec.bloques;
  if (!bloques) {
    const preset = PRESETS[spec.plantilla];
    if (!preset) fail(`falta 'bloques' o una 'plantilla' conocida`,
                      `plantillas: ${Object.keys(PRESETS).join(", ")} — o mandá bloques y componé libre`);
    bloques = preset(spec);
  }
  bloques = (bloques || []).filter(Boolean);
  if (!bloques.length) fail("la pieza no tiene ningún bloque");

  const esVertical = canvas.height / canvas.width > 1.5;
  const escalaVertical = esVertical ? 1.12 : 1;
  const pad = Math.round(canvas.width * (spec.margen || 0.09));
  const safe = SAFE_MARGIN[args.formato] || 0;
  const font = fonts.family || undefined;
  const paint = (hex) => rgba(...hexToRgba(hex));

  const children = bloques.map((b, i) => {
    if (b.tipo === "espacio") {
      return container({ style: { height: Math.round(b.alto || 24), width: 1 }, children: [] });
    }
    if (b.tipo === "barra") {
      const color = legible(resolve(b.color, roles.accent || ink), true, `barra #${i + 1}`);
      return container({ style: {
        height: Math.round(b.alto || 10), width: Math.round(b.ancho || 160),
        backgroundColor: paint(color), borderRadius: Math.round((b.alto || 10) / 2),
      }, children: [] });
    }
    const escala = SCALES[b.escala] || SCALES.bajada;
    const size = Math.round(canvas.width * escala * escalaVertical * (b.factor || 1));
    const grande = size >= Math.round(canvas.width * 0.05);
    const color = legible(resolve(b.color, ink), grande, `bloque #${i + 1}`);
    return text(String(b.texto ?? ""), {
      fontSize: size,
      lineHeight: b.interlinea || (grande ? 1.08 : 1.35),
      color: paint(color),
      fontFamily: font,
      fontWeight: b.peso || (grande ? 700 : 400),
      ...(b.italica ? { fontStyle: "italic" } : {}),
      ...(b.ancho ? { width: b.ancho } : {}),
    });
  });

  const vertical = VALIGN[spec.alineacion] || (esVertical ? "center" : "flex-end");
  const horizontal = HALIGN[spec.alinear] || "flex-start";

  const node = container({
    style: {
      width: canvas.width, height: canvas.height,
      display: "flex", flexDirection: "column",
      justifyContent: vertical, alignItems: horizontal,
      textAlign: spec.alinear === "centro" ? "center" : "left",
      paddingLeft: pad, paddingRight: pad,
      paddingTop: pad + safe, paddingBottom: pad + safe,
      backgroundColor: paint(background),
    },
    children,
  });

  return renderer.render(node, { width: canvas.width, height: canvas.height, format: "png" })
    .then((png) => {
      mkdirSync(dirname(args.out), { recursive: true });
      writeFileSync(args.out, png);
      console.log(JSON.stringify({
        ok: true,
        archivo: args.out,
        bytes: png.length,
        medidas: `${canvas.width}x${canvas.height}`,
        composicion: { bloques: bloques.length, alineacion: spec.alineacion || (esVertical ? "centro" : "abajo"),
                       alinear: spec.alinear || "izquierda" },
        colores: { fondo: background, tinta: ink },
        tipografia: fonts.family || "por defecto",
        avisos: warnings,
      }, null, 2));
    });
}

main();
